Repository at-cuongbao/AT-Internship-Fall-Winter-Football-Project-FE, pull requests merged in 2019-02, with the labels that each got.

#43 Feature/long create tournament registration form
  src/app/features/schedule/schedule.component.html
  src/app/features/schedule/schedule.component.ts
  src/app/features/tournament-registration/tournament-registration.component.html
  src/app/features/tournament-registration/tournament-registration.component.scss
  src/app/features/tournament-registration/tournament-registration.component.ts
  src/app/shared/services/api.service.ts
  src/app/shared/services/auth.service.ts
  src/scss/pages/_tournament-registration.scss
Labels: Sprint 3, [Status] Done, [Type] Task

#48 Feature/long dynamic error pages
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/page-not-found/page-not-found.component.html
  src/app/page-not-found/page-not-found.component.scss
  src/app/page-not-found/page-not-found.component.ts
  src/scss/pages/_all.scss
  src/scss/pages/_page-not-found.scss
Labels: Sprint 4, [Status] In Progressing, [Type] Task

#50 Feature/cuong create bracket page
  src/app/features/bracket/bracket.component.html
  src/app/features/bracket/bracket.component.ts
  src/scss/pages/_bracket.scss
Labels: Sprint 4, [Status] In Progressing, [Type] Task

#51 UI/UX Schedule page
  src/app/app.module.ts
  src/app/features/schedule/schedule.component.html
  src/app/features/schedule/schedule.component.ts
  src/app/shared/pipes/date-default.pipe.ts
  src/app/shared/pipes/question-mask.pipe.ts
  src/scss/layout/_layout.scss
  src/scss/pages/_schedules.scss
  src/scss/pages/_tournament-registration.scss
  src/scss/state/_state.scss
Labels: Sprint 4, [Status] In Progressing, [Type] Task

#64 Create football images
  src/app/app.module.ts
  src/app/features/home/football-images/football-images.component.html
  src/app/features/home/football-images/football-images.component.scss
  src/app/features/home/football-images/football-images.component.ts
  src/app/features/home/home.component.html
  src/assets/images/ibra.jpg
  src/assets/images/messi.png
  src/assets/images/neymar.png
  src/assets/images/our-team-main-wrap.jpg
  src/assets/images/ronaldo.png
  src/scss/pages/_all.scss
  src/scss/pages/_football-images.scss
Labels: Sprint 5, [Status] In Progressing, [Type] Task
